### PR TITLE
Resolve https://github.com/DevExpress/DevExtreme/issues/8552

### LINKED ISSUE #8552: compileGetter create incorrect getter for array of nested properties
### Steps to Reproduce:

1. Go to https://codepen.io/anon/pen/QXOgQL 
Example code:
```
var getter = DevExpress.data.utils.compileGetter(["B.Id",  "B.Key"]);
var obj =  { B: { Id:"B", Key: "key"}};
var idObj = getter(obj);
var idStr = JSON.stringify(idObj);
if(idObj.B.Id !== "B"){
  console.log("idObj.B.Id is incorrect. idObj.B.Id has to be 'B', but was", idObj.B.Id)
}
console.log("idObj -", idStr);
```
2. Check that function DevExpress.data.utils.compileGetter create getter and when getter executed part of nested properties in result has been lost.
3. I assume that error occurs because of line
`current = current[path[i]] = {}`
in function combineGetters, that line would overwrite part of result object
i think solution would be:
`current = current[path[i]] || (current[path[i]] = {});`

### PR DESCRIPTION
**Pull request by AlekseyMartynov**
Resolves https://github.com/DevExpress/DevExtreme/issues/8552

TODO: pick down to `19_1`, `18_2`

### CODE REVIEW

**Review by nightskylark — DISMISSED** [review]

File: js/core/utils/data.js [hunk 1]
```diff
@@ -126,11 +127,17 @@ var combineGetters = function(getters) {
             path = name.split(".");
             last = path.length - 1;
 
-            for(i = 0; i < last; i++) {
-                current = current[path[i]] = {};
+            for(i = 0; i <= last; i++) {
```
Comment (IlyaKhD) [inline js/core/utils/data.js]: What about moving the assignment outside the loop?
```
path = name.split(".");
last = path.length - 1;
if(last < 0) {
    return;
}

for(i = 0; i < last; i++) {
    pathItem = path[i];
    current = pathItem in current
        ? current[pathItem]
        : current[pathItem] = {};
}

current[path[last]] = value;
```

Comment (AlekseyMartynov) [reply js/core/utils/data.js]: Moved.

**Review by IlyaKhD — APPROVED** [review]

File: js/core/utils/data.js (hunk 1 above)
Comment (IlyaKhD) [reply js/core/utils/data.js]: :ok_hand:

**Review by dxvladislavvolkov — APPROVED** [review]
