### PR TITLE
Destroy Preact component on jQuery widget disposing

### LINKED ISSUE #186: Preact component inside the jQuery wrapper is not disposed properly
Check what generator works wrong

- [ ] Angular
- [ ] React
- [ ] Vue
- [x] jQuery

When jQuery wrapper is killed underlying preach component does not clear its effects etc.

### PR DESCRIPTION
**Pull request by pavelgruba**
Close https://github.com/DevExpress/devextreme-renovation/issues/186

### CODE REVIEW

**Review by LazyLahtak — DISMISSED** [review]

File: js/renovation/preact-wrapper/component.js [hunk 1]
```diff
@@ -22,6 +22,11 @@ export default class PreactWrapper extends DOMComponent {
         Preact.render(Preact.h(this._viewComponent, this.getAllProps(isFirstRender)), this.$element().get(0), container);
     }
 
+    _dispose() {
+        Preact.render(null, this.$element().get(0));
+        super.dispose();
```
Comment (roman-simionov) [inline js/renovation/preact-wrapper/component.js]:
```suggestion
        super._dispose();
```

**Review by roman-simionov — CHANGES_REQUESTED** [review]

**Review by roman-simionov — APPROVED** [review]

**Review by LazyLahtak — APPROVED** [review]
